### ISSUE TITLE
Set defaults

### ISSUE THREAD

**Issue by erikw** [klane/dotbot-ghq#2]
Hi, first thanks for this great plugin, I like it!

Would it be possible to set defaults for this plugin? I would like to always clone git repos with ssh using the ghq argument `p`.

Currently I do this:
```yaml
- ghq:
    - repo: erikw/templates
      flags: [-p]
```

But I'd like to do:
```yaml
- defaults:
    link:
      relink: true
    ghq:
      flags: [-p]


- ghq:
    - erikw/templates
```

From my testing it seems like it's currently not working.

Thanks!
